version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat: "
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(ci): "
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "custom"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps): "
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    patterns:
      - regex: 'GO_LINT_VERSION=(?<version>v[0-9]+\.[0-9]+\.[0-9]+)'
        dep-name-template: "golangci-lint"
      - regex: 'GO_SEC_URI=github\.com/securego/gosec/v2/cmd/gosec@(?<version>v[0-9]+\.[0-9]+\.[0-9]+)'
        dep-name-template: "gosec"
      - regex: 'GO_VULNCHECK_URI=golang\.org/x/vuln/cmd/govulncheck@(?<version>v[0-9]+\.[0-9]+\.[0-9]+)'
        dep-name-template: "govulncheck"
