FROM golang:1.23 AS builder

WORKDIR /src

COPY go.mod go.sum .

RUN go mod download

COPY *.go Makefile .

RUN make build

FROM quay.io/vshn/signalilo:v0.14.0 AS signalilo

FROM scratch

COPY --from=signalilo /usr/local/bin/signalilo /

COPY --from=builder /src/scrubbed /

USER 65532:65532

ENTRYPOINT ["/scrubbed"]
