FROM golang:1.22 as builder

WORKDIR /src

COPY go.mod go.sum .

RUN go mod download

COPY *.go Makefile .

RUN make build

FROM quay.io/vshn/signalilo:v0.14.0 AS signalilo

FROM registry.access.redhat.com/ubi9/ubi-micro:9.4

COPY --from=signalilo /usr/local/bin/signalilo /usr/local/bin/

COPY --from=builder /src/scrubbed /usr/local/bin/

EXPOSE 8080

EXPOSE 8443

ENTRYPOINT ["/usr/local/bin/scrubbed"]