kind: Deployment
apiVersion: apps/v1
metadata:
  name: scrubbed
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 20m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: signalilo
          command:
            - signalilo
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8888
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: signalilo
            - secretRef:
                name: signalilo
          image: scrubbed
