apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scrubbed

images:
  - name: scrubbed
    newName: quay.io/adfinis/scrubbed-signalilo
    newTag: v0.4.1

resources:
  - ../../base
  - secret-signalilo.yaml
  - configmap-signalilo.yaml

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
