apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - prometheusrule.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: alerting
      app.kubernetes.io/name: scrubbed
