{{- if .Values.signalilo.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scrubbed.fullname" . }}-signalilo
  labels:
    {{- include "scrubbed.labels" . | nindent 4 }}
    app.kubernetes.io/component: signalilo
data:
  SIGNALILO_ALERTMANAGER_PLUGINOUTPUT_ANNOTATIONS: {{ .Values.signalilo.alertmanagerPluginOutputAnnotations | quote }}
  SIGNALILO_ALERTMANAGER_PORT: {{ .Values.signalilo.listenPort | quote }}
  SIGNALILO_ICINGA_CA: {{ .Values.signalilo.icingaCA | quote }}
  SIGNALILO_ICINGA_DEBUG: {{ .Values.signalilo.debug | quote }}
  SIGNALILO_ICINGA_HOSTNAME: {{ .Values.signalilo.icingaHostname | quote }}
  SIGNALILO_ICINGA_URL: {{ .Values.signalilo.icingaURL | quote }}
  SIGNALILO_ICINGA_USERNAME: {{ .Values.signalilo.icingaUsername | quote }}
  SIGNALILO_UUID: {{ .Values.signalilo.icingaUUID | quote }}
{{- end -}}
