apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "scrubbed.labels" . | nindent 4 }}
    app.kubernetes.io/component: scrubbed
  name: {{ include "scrubbed.fullname" . }}
spec:
  progressDeadlineSeconds: 60
  replicas: {{ .Values.scrubbed.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "scrubbed.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "scrubbed.labels" . | nindent 8 }}
        app.kubernetes.io/component: scrubbed
    spec:
      containers:
      - command:
        - scrubbed
        envFrom:
        - configMapRef:
            name: {{ include "scrubbed.fullname" . }}
        image: "{{ .Values.scrubbed.image.repository }}:{{ default .Chart.AppVersion .Values.scrubbed.image.tag }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{ .Values.scrubbed.listenPort }}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: scrubbed
        ports:
        - containerPort: {{ .Values.scrubbed.listenPort }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{ .Values.scrubbed.listenPort }}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.scrubbed.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: {{ include "scrubbed.fullname" . }}
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        operator: Exists
{{- if .Values.scrubbed.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.scrubbed.nodeSelector | indent 8 }}
{{- end }}
