{{- if and .Values.signalilo.enabled .Values.signalilo.testSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "scrubbed.fullname" . }}-signalilo
  labels:
    {{- include "scrubbed.labels" . | nindent 4 }}
    app.kubernetes.io/component: signalilo
stringData::
  SIGNALILO_ALERTMANAGER_BEARER_TOKEN: foo
  SIGNALILO_ICINGA_PASSWORD: bar
{{- end -}}
