name: Release Container Image

on:
  schedule:
    - cron: '3 3 * * *'
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/adfinis/scrubbed
          tags: |
            type=schedule,pattern=nightly
            type=edge
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=ref,event=pr

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME}}
          password: ${{ secrets.QUAY_ACCESS_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
