name: Security
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  scan:
    strategy:
      matrix:
        go: ["1.22.5"]
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Run GoSec
        uses: securego/gosec@4a3bd8af174872c778439083ded7adbf3747e770 # v2.26.1
        with:
          args: -exclude-dir examples ./...

      - name: Run GoVulnCheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: ${{ matrix.go }}
          go-package: ./...
