# runs on each push to main and is responsible for creating new tags/releases
name: Create Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@db17a25cd5a42d2f8af79ff9b68a777b9ba82549 # v1.23.1
        with:
          github-token: ${{ secrets.PAT }}
          allow-initial-development-versions: true
