name: Test
on: pull_request
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: ruff
        run: |
          pip install -r requirements-dev.txt
          ruff format --check
          ruff check . --output-format=github
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run shellcheck
        id: shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
